name:                autopar
version:             0.1.0.0
github:              "oskarek/autopar"
license:             BSD3
author:              "Oskar Ek"
maintainer:          "oek@kth.se"
copyright:           "Copyright (c) 2019 Oskar Ek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oskarek/autopar#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- parallel
- stm
- containers
- split

library:
  source-dirs: src

executables:
  autopar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - autopar

tests:
  autopar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autopar
